<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\AI.Contracts\AI.Contracts.csproj"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting"/>
        <PackageReference Include="ModelContextProtocol.Core"/>
        <PackageReference Include="Pure.DI" PrivateAssets="all"/>
    </ItemGroup>
</Project>
