<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AI.Contracts\AI.Contracts.csproj" />
    <ProjectReference Include="..\AI.TextCorrection\AI.TextCorrection.csproj" />
    <Compile Include="..\AI.Contracts\Composition.cs" Link="Contracts\Composition.cs" />
    <Compile Include="..\AI.TextCorrection\Composition.cs" Link="TextCorrection\Composition.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <PackageReference Include="Pure.DI" PrivateAssets="all" />
    <PackageReference Include="Pure.DI.MS" />
    <PackageReference Include="Markdig" />
  </ItemGroup>
</Project>
