<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AI.Client.Contracts\AI.Client.Contracts.csproj" />
    <ProjectReference Include="..\AI.Client.Application\AI.Client.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <PackageReference Include="Pure.DI" PrivateAssets="all" />
    <PackageReference Include="Pure.DI.MS" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="HtmlSanitizer" />
  </ItemGroup>
</Project>
