<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="ModelContextProtocol.Core" />
    <PackageReference Include="JsonSchema.Net" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="Pure.DI" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AI.Client.Contracts\AI.Client.Contracts.csproj" />
  </ItemGroup>
</Project>
