<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\AI.Client.Mcp.BuiltIn\AI.Client.Mcp.BuiltIn.csproj" ReferenceOutputAssembly="false" Private="false" />
    <ProjectReference Include="..\AI.Client.Contracts\AI.Client.Contracts.csproj" />
    <ProjectReference Include="..\AI.Client.Server\AI.Client.Server.csproj" />
    <ProjectReference Include="..\AI.Client.Web\AI.Client.Web.csproj"
                      Aliases="AIClientWeb" />
    <Compile Include="..\AI.Client.Contracts\Composition.cs" Link="Contracts\Composition.cs" />
    <Compile Include="..\AI.Client.Server\Composition.cs" Link="Server\Composition.cs" />
    <Compile Include="..\AI.Client.Server\CommandLine\Composition.cs" Link="Server\CommandLine\Composition.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Pure.DI" PrivateAssets="all" />
    <PackageReference Include="Pure.DI.MS" />
  </ItemGroup>
  <Import Project="..\..\build\McpBuiltIn.targets" />
</Project>
