<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AI.Client.Application\AI.Client.Application.csproj" />
    <ProjectReference Include="..\AI.Client.Contracts\AI.Client.Contracts.csproj" />
  </ItemGroup>
</Project>
