namespace AI.Contracts.Navigation;

public sealed record AppNavigationTarget(string Id, string Label, string? Section,
    IReadOnlyList<string> Actions, bool? Visible = null, string? Hint = null, string? UiLabel = null,
    string? UiHint = null, bool? Enabled = null, string? State = null, string? Summary = null);

/// <summary>Semantic targets shared by the tool and the UI; selectors and coordinates stay in the client.</summary>
public interface IAppNavigationTargets
{
    IReadOnlyList<AppNavigationTarget> All { get; }
    AppNavigationTarget? Find(string id);
}

public sealed class AppNavigationTargets : IAppNavigationTargets
{
    private readonly IReadOnlyList<AppNavigationTarget> _definitions =
    [
        new("project", "Project in the sidebar", null, ["show", "hover", "click"], Hint: "Groups related chats, instructions, folder access, memory and skills. Use separate projects for unrelated work areas; selecting or naming a folder does not grant file access."),
        new("chat", "Chat in the sidebar", null, ["show", "hover", "click"], Hint: "Opens a conversation in this project. A new chat separates an unrelated goal from earlier discussion; requests use the selected conversation path rather than every stored message."),
        new("branch", "Chat branch", null, ["show", "hover", "click"], Hint: "Switches to an alternative path through the conversation. Shared earlier messages remain available; a branch is not an independent copy of project files or permissions."),
        new("projects.create", "New project", null, ["show", "hover", "click"], Hint: "Creates a project to organize related chats and their configuration. Folder access and tool permissions are configured separately."),
        new("project.menu", "Project menu", null, ["show", "hover", "click"], Hint: "Opens project actions and settings. Folder grants control which directories file tools can access; tool permissions control actions independently. A working directory is not a process sandbox."),
        new("project.settings", "Project settings", "ProjectSettings", ["show"], Hint: "Configures this project's name, description and instructions. Project settings apply to its chats; appearance and other client preferences belong to this client."),
        new("project.name", "Project name", "ProjectSettings", ["show", "focus", "set_value"], Hint: "Names the project in the sidebar. Choose a name that identifies the codebase or work area; changing it does not move files or change access."),
        new("project.description", "Project description", "ProjectSettings", ["show", "focus", "set_value"], Hint: "Describes the project's purpose so related work is easier to identify. A description is not a filesystem grant or a tool permission."),
        new("chat.new", "New chat", null, ["show", "hover", "click"], Hint: "Starts another conversation in this project. Use it for a separate goal while retaining the project's configuration."),
        new("chat.composer", "Message editor", null, ["show", "hover", "focus", "set_value"], Hint: "Write the goal, constraints and a way to check success. The model receives the selected conversation path, applicable instructions, references and available tool definitions; it does not automatically see every file or open panel. Use @ for references and / for skills."),
        new("chat.context", "Add context menu", null, ["show", "hover", "click"], Hint: "Adds selected references, files, reviews or other evidence to the next request. Focused evidence is more useful than unrelated bulk text. Adding context does not authorize changing its source or grant tool access."),
        new("chat.fork", "Fork from a message", null, ["show", "hover", "click"], Hint: "Starts an alternative conversation path from this message while keeping earlier replies. Later messages on the original path are not included in the new path; project files are shared."),
        new("chat.edit_branch", "Edit a message as a branch", null, ["show", "hover", "click"], Hint: "Edits this message to start an alternative conversation path. Earlier shared history is retained; this does not create a separate copy of project files."),
        new("chat.send", "Send message", null, ["show", "hover", "click"], Hint: "Applies the current send action. Enter sends, Ctrl+Enter queues, Shift+Enter inserts a newline, Ctrl+Alt+Enter sends in a forked session, and Ctrl+Shift+Enter interrupts and sends now. Queued messages on one branch run in sequence."),
        new("chat.text_correction", "Text correction switch", null, ["show", "hover"], Hint: "With no selected languages, opens language settings. Otherwise pauses or resumes local text correction without forgetting the selected languages."),
        new("chat.branches", "Branch picker", null, ["show", "hover", "click"], Hint: "Chooses an alternative conversation path. Earlier shared messages remain the same; later requests follow the selected path."),
        new("chat.widgets", "Chat widgets", null, ["show", "hover", "click"], Hint: "Shows or hides the widget column beside this chat. Widgets expose usage, tools, files and alternative branches so you can inspect the work; closing the column does not delete chat data."),
        new("workspace.sidebar", "Left sidebar", null, ["show", "hover"], Hint: "Organizes projects, chats and branches. Drag the separator to resize it; use the header toggle or Ctrl+B to hide or restore it for more reading space."),
        new("workspace.sidebar.toggle", "Toggle left sidebar", null, ["show", "hover", "click"], Hint: "Hides or restores the left sidebar (Ctrl+B). Projects and chats remain available when the panel is hidden."),
        new("workspace.search", "Open message search", null, ["show", "hover", "click"], Hint: "Opens message search (Ctrl+K). Search reads stored conversations without making a model request; it does not search project files or the web."),
        new("search", "Message search panel", "Search", ["show"], Hint: "Searches stored messages across chats. Enter at least two characters; include archived chats when needed. Up/Down select a result, Enter opens it, and Esc closes search."),
        new("search.query", "Message search query", "Search", ["show", "hover", "focus"], Hint: "Enter at least two characters from a message you want to find. This searches stored conversation text, not files, the web or what a model remembers."),
        new("search.archived", "Include archived chats", "Search", ["show", "hover"], Hint: "Includes messages from archived chats in search. This does not restore or modify those chats."),
        new("search.results", "Message search results", "Search", ["show", "hover"], Hint: "Groups matching messages by chat and opens the matching point in a conversation. Up/Down select a result and Enter opens it. F3 and Shift+F3 step through rendered occurrences in the open chat."),
        new("search.close", "Close message search", "Search", ["show", "hover"], Hint: "Closes message search and clears its query (Esc). Stored messages and chats are unchanged."),
        new("workspace.notifications", "Open notifications", null, ["show", "hover", "click"], Hint: "Opens recent chat events, failures and work needing attention. Opening history marks events seen; seeing an event does not resolve an action it requires."),
        new("notifications", "Notification history", null, ["show", "hover"], Hint: "Shows recent events saved on this client, including completion, failures and work needing attention. All and Needs attention filter the history. An event may open its associated chat; this bounded history is not a complete audit log."),
        new("notifications.toast", "Current notification popup", null, ["show", "hover"], Hint: "Shows a recent chat event briefly. Hovering pauses dismissal; closing the popup keeps its history entry. An event needing attention can remain unresolved after it is seen."),
        new("widgets", "Right widget sidebar", "Widgets", ["show"], Hint: "Shows summaries beside the conversation. Choose which widgets appear, resize the column and arrange widgets to keep relevant evidence visible."),
        new("widgets.menu", "Choose shown widgets", "Widgets", ["show", "hover", "click"], Hint: "Chooses which widgets are shown. Hiding a widget changes this client's layout without deleting the chat data it summarizes."),
        new("widgets.collapse", "Collapse or expand all widgets", "Widgets", ["show", "hover"], Hint: "Collapses or expands all visible widgets. Their data remains available; expanding a widget reveals its details again."),
        new("widgets.close", "Close the widget sidebar", "Widgets", ["show", "hover"], Hint: "Closes the widget column. Reopen it from the chat header; chat data and the saved widget arrangement remain available."),
        new("widgets.chat-usage", "Usage widget", "Widgets", ["show", "hover"], Hint: "Shows model token usage, context budget and estimated cost. A turn can contain several model requests and tool calls. Token estimates are not provider billing; summaries can reduce model-facing history while keeping the visible transcript."),
        new("widgets.chat-files", "Files widget", "Widgets", ["show", "hover"], Hint: "Shows files changed by this chat, with lines added and removed. Inspect actual changes and supporting evidence; a proposed edit in model prose is not proof that a file changed."),
        new("widgets.chat-tools", "Tools widget", "Widgets", ["show", "hover"], Hint: "Shows tool calls and their outcomes. The model proposes arguments; the application checks permissions, executes permitted calls and returns results for subsequent model requests."),
        new("widgets.chat-performance", "Performance widget", "Widgets", ["show", "hover"], Hint: "Shows wall-clock time, throughput and how request time was spent for the whole chat or last turn. Waiting for a user decision or tool execution differs from generating a model response."),
        new("widgets.chat-subtasks", "Subtasks widget", "Widgets", ["show", "hover"], Hint: "Shows delegated work on another model, with requests, tokens and its share of the whole chat or last turn. Delegation separates tasks but adds requests and coordination; inspect each outcome."),
        new("widgets.chat-knowledge", "Knowledge widget", "Widgets", ["show", "hover"], Hint: "Shows files and pages the assistant read on the visible branch, grouped by tool and recent paths. This is evidence of reading activity, not proof that every relevant source was read or understood."),
        new("widgets.chat-timeline", "Timeline widget", "Widgets", ["show", "hover"], Hint: "Shows one row per turn on the visible branch: start time, duration, requests, tokens, tools and files. Use it to relate activity to outcomes."),
        new("widgets.chat-branches", "Branches widget", "Widgets", ["show", "hover"], Hint: "Shows stored branches with title, depth, message count, child branches and head timestamp. Selecting a branch changes the visible conversation path while keeping shared project files."),
        new("widgets.app-guide", "Application guide widget", "Widgets", ["show", "hover"], Hint: "Choose a learning topic and show or demonstration mode. A running tour provides Pause and Stop; completed topics track learning progress on this client."),
        new("widgets.chat-usage.title", "Collapse one widget", "Widgets", ["show", "hover"], Hint: "Collapses or expands this widget. Collapsing hides its details without deleting the underlying data."),
        new("widgets.chat-usage.move", "Move one widget", "Widgets", ["show", "hover"], Hint: "Moves this widget in the column. Drag its handle, or use the keyboard controls when focused; the order is a client preference."),
        new("widgets.chat-usage.hide", "Hide one widget", "Widgets", ["show", "hover"], Hint: "Hides this widget. Restore it from the widget chooser; its underlying chat data is retained."),
        new("chat.demo", "Demo chat set up by the guide", null, ["show", "click"], Hint: "Creates and opens a temporary example conversation with a question and reply without a model request. The guide removes it after the tour unless you add to it."),
        new("settings", "Application settings", "Settings", ["show"], Hint: "Configures appearance, usage display, model helpers, text correction, sounds and guide preferences. Client preferences apply here; settings stored by the Host apply across its clients."),
        new("settings.appearance.theme", "Theme", "Settings", ["show", "hover", "focus", "set_value"], Hint: "Chooses this client's light, dark or system theme. System follows the operating system's appearance."),
        new("settings.appearance.accent", "Accent color", "Settings", ["show", "hover"], Hint: "Chooses the accent color used for highlights and active controls on this client."),
        new("settings.appearance.corners", "Corner roundness", "Settings", ["show", "hover"], Hint: "Adjusts corner roundness on this client without changing application behavior."),
        new("settings.chat.context_usage", "Context window usage", "Settings", ["show", "hover"], Hint: "Shows context window usage near the message editor. Conversation history, instructions, references and tool definitions share a finite input budget with reserved response space."),
        new("settings.chat.turn_tokens", "Tokens per turn", "Settings", ["show", "hover"], Hint: "Shows token usage beside each turn's time. A turn may include several requests, so its total can exceed a single response's tokens.", Summary: "Next to each turn's time"),
        new("settings.chat.live_notes", "Notes while working", "Settings", ["show", "hover", "focus", "set_value"], Hint: "Sets how many of the model's latest notes stay under a running turn's row, from 1 to 5. A new note appears at the bottom and the oldest one folds away above it; all notes remain in the expanded turn.", Summary: "Latest notes under a running turn"),
        new("settings.chat.helpers", "Model helpers", "Settings", ["show", "hover"], Hint: "Configures automatic chat helpers. Each helper makes an additional request to the chat's connection, consuming time and tokens. Disabling a helper does not disable ordinary chat.", Summary: "Each makes one more request to the chat's connection"),
        new("settings.chat.auto_title", "Automatic chat titles", "Settings", ["show", "hover"], Hint: "Uses an additional model request to name a new chat after its first answer. This Host setting applies across its clients."),
        new("settings.chat.reply_suggestions", "Reply suggestions", "Settings", ["show", "hover"], Hint: "Uses an additional model request to suggest possible next messages. Suggestions do not send themselves; this Host setting applies across its clients."),
        new("settings.chat.review_suggestions", "Review comment suggestions", "Settings", ["show", "hover"], Hint: "Uses an additional model request to suggest review comments. Check the concrete behavior, location and consequence before using a finding; suggestions are not evidence of correctness."),
        new("settings.chat.skill_routing", "Automatic skill selection", "Settings", ["show", "hover"], Hint: "Uses an additional model request to select a relevant skill. Selection is a suggestion, not a quality guarantee or permission to bypass approvals."),
        new("settings.chat.text_correction", "Text correction", "Settings", ["show", "hover"], Hint: "Corrects typed words locally using selected language dictionaries, without a model request. Completed words are checked after a separator and the final word before sending. Ambiguous spelling changes are skipped; pasted text stays excluded until manually edited. Ctrl+Z immediately restores a correction and suppresses repeating it."),
        new("settings.chat.text_correction.enabled", "Correct while typing", "Settings", ["show", "hover"], Hint: "Pauses or resumes correction without clearing selected languages. The button beside the message editor controls the same setting; with no languages selected it opens language settings.", Summary: "The button in the message editor pauses or resumes correction. If no languages are selected, it opens these language settings."),
        new("settings.chat.text_correction.languages", "Text correction languages", "Settings", ["show", "hover"], Hint: "Select one language for spelling correction, or two or more for wrong-layout correction as well. No languages are selected by default; choose only the languages you type in. Two languages are recommended for layout performance. Choices are saved on this client.", Summary: "Select a language for spelling correction. Select two or more to also correct text typed in the wrong layout."),
        new("settings.chat.text_correction.en", "English spelling and layout correction", "Settings", ["show", "hover"], Hint: "Selects English (US) for local spelling correction. With another selected language, wrong-layout correction is also enabled."),
        new("settings.chat.text_correction.ru", "Russian spelling and layout correction", "Settings", ["show", "hover"], Hint: "Selects Russian for local spelling correction. With another selected language, wrong-layout correction is also enabled."),
        new("settings.chat.text_correction.fr", "French spelling and layout correction", "Settings", ["show", "hover"], Hint: "Selects French for local spelling correction. With another selected language, wrong-layout correction is also enabled."),
        new("settings.chat.text_correction.es", "Spanish spelling and layout correction", "Settings", ["show", "hover"], Hint: "Selects Spanish for local spelling correction. With another selected language, wrong-layout correction is also enabled."),
        new("settings.guide.enabled", "Guide suggestions", "Settings", ["show", "hover", "click", "set_value"], Hint: "Allows guide invitations at most once a day while this client is idle. Invitations do not start a tour automatically; you can start a topic yourself from the Guide widget.", Summary: "At most once a day. Unanswered invitations close automatically."),
        new("settings.guide.idle", "Guide idle interval", "Settings", ["show", "focus", "set_value"], Hint: "Sets how long this client must be idle before a guide invitation may appear. Active typing, scrolling or another running interaction delays invitations."),
        new("settings.guide.progress", "Learning progress", "Settings", ["show", "hover"], Hint: "Shows completed learning topics on this client. Resetting progress makes topics available for learning again without changing projects or conversations."),
        new("settings.connections", "Model connections", "Connections", ["show"], Hint: "Configures model endpoints, credentials and model choices. Chats and the guide need an enabled connection. Requests go to the configured endpoint even when conversations are stored locally."),
        new("settings.connections.add", "Add connection", "Connections", ["show", "hover", "click"], Hint: "Adds a model connection. Fill in its endpoint URL, credential if needed and model, then enable it. A local model server is also a separate connection."),
        new("settings.connections.close", "Save and close connections", "Connections", ["show", "hover"], Hint: "Saves connection changes and closes the panel. Once a connection is enabled, start a guide topic from the Guide widget."),
        new("settings.connection.enabled", "Connection enabled", "Connections", ["show", "hover"], Hint: "Allows this connection to answer chats. The guide can borrow an enabled connection; a disabled connection cannot answer requests."),
        new("settings.connection.default", "Default connection", "Connections", ["show", "hover"], Hint: "Uses this connection when a chat or project does not specify another. The connection selected in this editor need not be the one used by the active chat.", Summary: "Used when a chat names no other"),
        new("settings.connection.subtasks", "Connection for subtasks", "Connections", ["show", "hover"], Hint: "Makes this connection eligible for delegated work. Delegation adds requests and coordination; eligibility does not guarantee selection for every task.", Summary: "Delegated work may go here"),
        new("settings.connection.url", "Model endpoint URL", "Connections", ["show", "hover"], Hint: "The base address of an OpenAI-compatible model API, such as https://api.openai.com/v1 or a local server. This is the endpoint that receives model requests, not a project folder or a model name."),
        new("settings.connection.credential", "Model API key", "Connections", ["show", "hover"], Hint: "The API key authorizing calls to this endpoint. Create it in the provider's account; local servers may not need one. It is stored encrypted on this computer and must never be included in guide context."),
        new("settings.connection.model", "Model picker", "Connections", ["show", "hover"], Hint: "Selects or names a model at this endpoint. The model list loads from the configured provider; capability, latency and context limits depend on the actual model and endpoint."),
        new("settings.connection.capability", "Connection capability", "Connections", ["show", "hover"], Hint: "Rates capability for connection selection during delegated work. This is a selection hint, not an independently measured score or a guarantee of answer quality."),
        new("settings.connection.good_for", "Connection specialties", "Connections", ["show", "hover"], Hint: "Describes tasks this connection suits, such as vision or long context. Delegated work uses this selection hint alongside capability; verify the model's outputs."),
        new("settings.connection.context_window", "Context window limit", "Connections", ["show", "hover"], Hint: "Overrides the total token budget for input and reserved response space. Empty uses the resolved model default. Increasing this setting does not increase the endpoint's real model limit; exact evidence may need reattaching after history is summarized."),
        new("settings.connection.reserved_output", "Reserved response tokens", "Connections", ["show", "hover"], Hint: "Keeps space free for the model response when planning context. Empty uses the resolved model default. More response reserve leaves less room for history, instructions, references and tool definitions."),
        new("settings.connection.input_price", "Input token price", "Connections", ["show", "hover"], Hint: "Estimates US dollars per million uncached input tokens when the endpoint does not quote a request cost. This is a fallback estimate, not a provider billing setting."),
        new("settings.connection.output_price", "Output token price", "Connections", ["show", "hover"], Hint: "Estimates US dollars per million output tokens when the endpoint does not quote a request cost. This changes estimates, not the price charged by the provider."),
        new("settings.connection.cached_price", "Cached input token price", "Connections", ["show", "hover"], Hint: "Estimates US dollars per million cached input tokens. Empty uses the input price. Caching depends on endpoint support and is not guaranteed.", Summary: "Empty: same as input"),
        new("settings.tools", "Application tools", "MCP", ["show"], Hint: "Configures application and MCP tools, server availability, permissions and execution limits. Tools perform operations; skills coordinate them and memory supplies facts. Folder grants and tool permissions are independent; a working directory does not sandbox a process."),
        new("settings.tools.decision", "Global tool permission", "MCP", ["show", "hover"], Hint: "Sets this tool's global default: Allow executes without asking, Ask pauses for approval, and Deny refuses calls. Chat rules override project rules, which override global rules. Ask is the fallback without a matching rule; disabled or denied servers still block execution."),
        new("project.permissions", "Project tool permissions", "ProjectPermissions", ["show"], Hint: "Shows this project's tool permission overrides. Chat rules override project rules, which override global rules; server restrictions still apply. Reset removes an override and restores its inherited fallback rather than necessarily denying a tool."),
        new("project.permissions.overrides", "Project permission overrides", "ProjectPermissions", ["show", "hover", "click"], Hint: "Shows only rules saved for this project. An empty list means inherited global rules apply. Reset removes a project override; Reset all affects this scope only."),
        new("project.permissions.effective", "Effective project permissions", "ProjectPermissions", ["show", "hover", "click"], Hint: "Shows merged saved rules and their sources after chat, project and global precedence. This is not an exhaustive list of all tools or server restrictions. Inspect the fallback before resetting a rule."),
        new("chat.permissions", "Chat tool permissions", "ChatPermissions", ["show"], Hint: "Shows this chat's tool permission overrides. Use the narrowest suitable scope; global permission applies across projects on this Host. Reset restores inherited project or global rules."),
        new("chat.permissions.overrides", "Chat permission overrides", "ChatPermissions", ["show", "hover", "click"], Hint: "Shows only rules saved for this chat. An empty list means inherited project or global rules apply. Reset all removes overrides at this scope only."),
        new("chat.permissions.effective", "Effective chat permissions", "ChatPermissions", ["show", "hover", "click"], Hint: "Shows merged saved rules, their source and inherited fallback. An inherited Allow is still subject to server restrictions and folder access; it does not guarantee successful execution."),
        new("chat.approval", "Pending tool approval", null, ["show", "hover"], Hint: "Inspect the actual tool, arguments, paths and intended effect before deciding. Allow once and Deny affect this call without saving a rule. Other allow choices save a chat, project or global rule; global permission requires separate confirmation."),
        new("chat.approval.once", "Allow the pending call once", null, ["show", "hover"], Hint: "Runs this pending call once without saving a permission rule. Check its actual arguments and intended effect first."),
        new("chat.approval.deny", "Refuse the pending call", null, ["show", "hover"], Hint: "Refuses this pending call without saving a permission rule. A stored Deny policy in settings is a separate, persistent decision."),
        new("settings.skills", "Skills", "Skills", ["show"], Hint: "Manages reusable procedures. Built-ins are read-only, personal skills apply across projects and project skills apply to one project. Project skills override personal skills with the same ID; built-in IDs are reserved. Use / in the editor to select a skill. A skill does not grant tool or folder access."),
        new("settings.memory", "Memory", "Memory", ["show"], Hint: "Stores reusable facts, preferences and decisions, indexed and read as needed. Project instructions supply rules; skills supply procedures. Memory is not an unlimited replay of every stored conversation."),
        new("project.instructions", "Project instructions", "ProjectSettings", ["show", "focus", "set_value"], Hint: "Supplies rules for work in this project's chats. When enabled, instructions can include AGENTS.md or CLAUDE.md at granted roots; nested files are not all loaded automatically. Instructions do not grant file or tool access."),
        new("settings.sounds.notifications", "Notification sound", "Settings", ["show", "hover", "click", "set_value"], Hint: "Plays sounds for supported notification events on this client. Availability of operating-system notifications and badges depends on the host."),
        new("settings.sounds.other", "Other sounds", "Settings", ["show", "hover"], Hint: "Controls other application sounds on this client. This preference does not change model behavior.")
    ];

    public AppNavigationTargets()
    {
        const string template = "widgets.chat-usage";
        var widgets = _definitions.Where(target => target.Id != template
            && (target.Id.StartsWith("widgets.chat-", StringComparison.Ordinal) || target.Id == "widgets.app-guide")
            && target.Id.LastIndexOf('.') == "widgets".Length);
        var actions = _definitions.Where(target => target.Id.StartsWith(template + ".", StringComparison.Ordinal));
        All = [.. _definitions, .. widgets.SelectMany(widget => actions.Select(action =>
            action with { Id = widget.Id + action.Id[template.Length..] }))];
    }

    public IReadOnlyList<AppNavigationTarget> All { get; }

    public AppNavigationTarget? Find(string id) => All.FirstOrDefault(target => target.Id == id);
}
