namespace AI.Contracts.Navigation;

public sealed record AppNavigationTarget(string Id, string Label, string? Section,
    IReadOnlyList<string> Actions, bool? Visible = null);

/// <summary>Semantic targets shared by the tool and the UI; selectors and coordinates stay in the client.</summary>
public sealed class AppNavigationTargets
{
    public IReadOnlyList<AppNavigationTarget> All { get; } =
    [
        new("project", "Project in the sidebar", null, ["show", "hover", "click"]),
        new("chat", "Chat in the sidebar", null, ["show", "hover", "click"]),
        new("branch", "Chat branch", null, ["show", "hover", "click"]),
        new("projects.create", "New project", null, ["show", "hover", "click"]),
        new("project.menu", "Project menu", null, ["show", "hover", "click"]),
        new("project.settings", "Project settings", "ProjectSettings", ["show"]),
        new("project.name", "Project name", "ProjectSettings", ["show", "focus", "set_value"]),
        new("project.description", "Project description", "ProjectSettings", ["show", "focus", "set_value"]),
        new("chat.new", "New chat", null, ["show", "hover", "click"]),
        new("chat.composer", "Message editor", null, ["show", "hover", "focus", "set_value"]),
        new("chat.context", "Add context menu", null, ["show", "hover", "click"]),
        new("chat.fork", "Fork from a message", null, ["show", "hover", "click"]),
        new("chat.edit_branch", "Edit a message as a branch", null, ["show", "hover", "click"]),
        new("chat.send", "Send message", null, ["show", "hover", "click"]),
        new("chat.branches", "Branch picker", null, ["show", "hover", "click"]),
        new("chat.widgets", "Chat widgets", null, ["show", "hover", "click"]),
        new("workspace.sidebar", "Left sidebar", null, ["show", "hover"]),
        new("workspace.sidebar.toggle", "Toggle left sidebar", null, ["show", "hover", "click"]),
        new("workspace.search", "Open message search", null, ["show", "hover", "click"]),
        new("search", "Message search panel", "Search", ["show"]),
        new("search.query", "Message search query", "Search", ["show", "hover", "focus"]),
        new("search.archived", "Include archived chats", "Search", ["show", "hover"]),
        new("search.results", "Message search results", "Search", ["show", "hover"]),
        new("search.close", "Close message search", "Search", ["show", "hover"]),
        new("workspace.notifications", "Open notifications", null, ["show", "hover", "click"]),
        new("notifications", "Notification history", null, ["show", "hover"]),
        new("notifications.toast", "Current notification popup", null, ["show", "hover"]),
        new("widgets", "Right widget sidebar", "Widgets", ["show"]),
        new("widgets.menu", "Choose shown widgets", "Widgets", ["show", "hover", "click"]),
        new("widgets.collapse", "Collapse or expand all widgets", "Widgets", ["show", "hover"]),
        new("widgets.close", "Close the widget sidebar", "Widgets", ["show", "hover"]),
        new("widgets.chat-usage", "Usage widget", "Widgets", ["show", "hover"]),
        new("widgets.chat-files", "Files widget", "Widgets", ["show", "hover"]),
        new("widgets.chat-tools", "Tools widget", "Widgets", ["show", "hover"]),
        new("widgets.chat-performance", "Performance widget", "Widgets", ["show", "hover"]),
        new("widgets.chat-subtasks", "Subtasks widget", "Widgets", ["show", "hover"]),
        new("widgets.chat-knowledge", "Knowledge widget", "Widgets", ["show", "hover"]),
        new("widgets.chat-timeline", "Timeline widget", "Widgets", ["show", "hover"]),
        new("widgets.chat-branches", "Branches widget", "Widgets", ["show", "hover"]),
        new("widgets.app-guide", "Application guide widget", "Widgets", ["show", "hover"]),
        new("widgets.chat-usage.title", "Collapse one widget", "Widgets", ["show", "hover"]),
        new("widgets.chat-usage.move", "Move one widget", "Widgets", ["show", "hover"]),
        new("widgets.chat-usage.hide", "Hide one widget", "Widgets", ["show", "hover"]),
        new("chat.demo", "Demo chat set up by the guide", null, ["show", "click"]),
        new("settings", "Application settings", "Settings", ["show"]),
        new("settings.appearance.theme", "Theme", "Settings", ["show", "hover", "focus", "set_value"]),
        new("settings.appearance.accent", "Accent color", "Settings", ["show", "hover"]),
        new("settings.appearance.corners", "Corner roundness", "Settings", ["show", "hover"]),
        new("settings.chat.context_usage", "Context window usage", "Settings", ["show", "hover"]),
        new("settings.chat.turn_tokens", "Tokens per turn", "Settings", ["show", "hover"]),
        new("settings.chat.helpers", "Model helpers", "Settings", ["show", "hover"]),
        new("settings.chat.auto_title", "Automatic chat titles", "Settings", ["show", "hover"]),
        new("settings.chat.reply_suggestions", "Reply suggestions", "Settings", ["show", "hover"]),
        new("settings.chat.review_suggestions", "Review comment suggestions", "Settings", ["show", "hover"]),
        new("settings.chat.skill_routing", "Automatic skill selection", "Settings", ["show", "hover"]),
        new("settings.guide.enabled", "Guide suggestions", "Settings", ["show", "hover", "click", "set_value"]),
        new("settings.guide.idle", "Guide idle interval", "Settings", ["show", "focus", "set_value"]),
        new("settings.guide.progress", "Learning progress", "Settings", ["show", "hover"]),
        new("settings.connections", "Model connections", "Connections", ["show"]),
        new("settings.connections.add", "Add connection", "Connections", ["show", "hover", "click"]),
        new("settings.connections.close", "Save and close connections", "Connections", ["show", "hover"]),
        new("settings.connection.enabled", "Connection enabled", "Connections", ["show", "hover"]),
        new("settings.connection.default", "Default connection", "Connections", ["show", "hover"]),
        new("settings.connection.subtasks", "Connection for subtasks", "Connections", ["show", "hover"]),
        new("settings.connection.url", "Model endpoint URL", "Connections", ["show", "hover"]),
        new("settings.connection.credential", "Model API key", "Connections", ["show", "hover"]),
        new("settings.connection.model", "Model picker", "Connections", ["show", "hover"]),
        new("settings.connection.capability", "Connection capability", "Connections", ["show", "hover"]),
        new("settings.connection.good_for", "Connection specialties", "Connections", ["show", "hover"]),
        new("settings.connection.context_window", "Context window limit", "Connections", ["show", "hover"]),
        new("settings.connection.reserved_output", "Reserved response tokens", "Connections", ["show", "hover"]),
        new("settings.connection.input_price", "Input token price", "Connections", ["show", "hover"]),
        new("settings.connection.output_price", "Output token price", "Connections", ["show", "hover"]),
        new("settings.connection.cached_price", "Cached input token price", "Connections", ["show", "hover"]),
        new("settings.tools", "Application tools", "MCP", ["show"]),
        new("settings.tools.decision", "Global tool permission", "MCP", ["show", "hover"]),
        new("project.permissions", "Project tool permissions", "ProjectPermissions", ["show"]),
        new("project.permissions.overrides", "Project permission overrides", "ProjectPermissions", ["show", "hover", "click"]),
        new("project.permissions.effective", "Effective project permissions", "ProjectPermissions", ["show", "hover", "click"]),
        new("chat.permissions", "Chat tool permissions", "ChatPermissions", ["show"]),
        new("chat.permissions.overrides", "Chat permission overrides", "ChatPermissions", ["show", "hover", "click"]),
        new("chat.permissions.effective", "Effective chat permissions", "ChatPermissions", ["show", "hover", "click"]),
        new("chat.approval", "Pending tool approval", null, ["show", "hover"]),
        new("chat.approval.once", "Allow the pending call once", null, ["show", "hover"]),
        new("chat.approval.deny", "Refuse the pending call", null, ["show", "hover"]),
        new("settings.skills", "Skills", "Skills", ["show"]),
        new("settings.memory", "Memory", "Memory", ["show"]),
        new("project.instructions", "Project instructions", "ProjectSettings", ["show", "focus", "set_value"]),
        new("settings.sounds.notifications", "Notification sound", "Settings", ["show", "hover", "click", "set_value"]),
        new("settings.sounds.other", "Other sounds", "Settings", ["show", "hover"])
    ];

    public AppNavigationTarget? Find(string id) => All.FirstOrDefault(target => target.Id == id);
}
