<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AI.Client.Mcp.BuiltIn\AI.Client.Mcp.BuiltIn.csproj" />
    <ProjectReference Include="..\..\src\AI.Client.Mcp.App\AI.Client.Mcp.App.csproj" />
    <ProjectReference Include="..\..\src\AI.Client.Application\AI.Client.Application.csproj" />
    <ProjectReference Include="..\..\src\AI.Client.Domain\AI.Client.Domain.csproj" />
    <ProjectReference Include="..\..\src\AI.Client.Infrastructure\AI.Client.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <Target Name="CopyDefaultMcpServer" AfterTargets="Build">
    <ItemGroup><DefaultMcpFiles Include="..\..\src\AI.Client.Mcp.BuiltIn\bin\$(Configuration)\$(TargetFramework)\*" /></ItemGroup>
    <Copy SourceFiles="@(DefaultMcpFiles)" DestinationFolder="$(OutDir)mcp" SkipUnchangedFiles="true" />
  </Target>
</Project>
