namespace AI.Contracts.Tools;

/// <summary>
/// How one tool invocation is described to the user. Every field is derived deterministically from
/// the tool's identity, its arguments and its actual result — never generated by a second model
/// call, and never counted from anything the Host did not observe. If the system only knows how
/// many calls were made, the summary says "calls", not "files".
/// </summary>
public sealed record ToolCallPresentation(
    string Title,
    string? Detail,
    ToolSafety Safety);

/// <summary>
/// The result of one invocation, split into what fits a single collapsed row
/// (<paramref name="Summary"/>), what belongs in an expanded detail list
/// (<paramref name="Facts"/>), and bulk text that must stay out of the DOM until asked for
/// (<paramref name="Body"/>).
/// </summary>
public sealed record ToolResultPresentation(
    string Summary,
    ToolResultSeverity Severity,
    IReadOnlyList<ToolFact> Facts,
    string? Body,
    ToolBodyFormat BodyFormat = ToolBodyFormat.PlainText);

public sealed record ToolFact(string Label, string Value);

public enum ToolResultSeverity
{
    Ok,

    /// <summary>Completed, but with something the user should notice: truncation, a non-zero exit, a timeout.</summary>
    Warning,
    Error,
}

public enum ToolBodyFormat
{
    PlainText,
    Diff,
}

/// <summary>
/// How much of the workspace an invocation can touch, for UI emphasis only.
/// </summary>
/// <remarks>
/// Derived from MCP annotations, which the specification defines as hints supplied by the server
/// describing its own tools. They are not a trust boundary: approval prompts, directory grants and
/// policy decisions are the Host's, and must never be relaxed because a server called itself
/// read-only.
/// </remarks>
public enum ToolSafety
{
    /// <summary>The server said nothing, so nothing is claimed.</summary>
    Unknown,
    ReadOnly,
    Mutating,
    Destructive,
}
