<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AI.Client.Mcp.BuiltIn\AI.Client.Mcp.BuiltIn.csproj" />
    <ProjectReference Include="..\..\src\AI.Client.Server\AI.Client.Server.csproj" />
    <Compile Include="..\..\src\AI.Client.Contracts\Composition.cs" Link="Contracts\Composition.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Pure.DI" PrivateAssets="all" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <Import Project="..\..\build\McpBuiltIn.targets" />
</Project>
